<?php
/**
 * @file
 * Main module file with hooks implementations.
 */
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;


/**
 * Implements hook_theme().
 */
function vols_theme($existing, $type, $theme, $path) {
  return [
    'front_vols_list' => [
      'variables' => [
        'vols' => NULL,
        'type' => 'departure'
      ],
      'template' => 'front/vols-list',
    ],

    'admin_vols_list' => [
      'variables' => [
        'vols' => NULL
      ],
      'template' => 'admin/vols/list',
    ],

    'admin_status_list' => [
      'variables' => [
        'status' => NULL
      ],
      'template' => 'admin/status/list',
    ],

  ];
}

/**
 * Implements hook_library_info().
 */
function vols_library_info() {
  $libraries = [];

  $libraries['vols/custom'] = [
    'title' => 'Custom CSS and JavaScript',
    'version' => '1.0',
    'css' => [
      'assets/css/vols.css' => [],
    ],
    'js' => [
      'assets/js/vols.js' => [],
    ],
  ];

  return $libraries;
}

/**
 * Implements hook_page_attachments().
 */
function vols_page_attachments(array &$attachments) {
  // Attache le fichier CSS et js personnalisé à chaque page.
  $attachments['#attached']['library'][] = 'vols/custom';
}
