<?php
/**
 * @file
 * Main module file with hooks implementations.
 */
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;


/**
 * Implements hook_theme().
 */
function vols_theme($existing, $type, $theme, $path) {
  return [
    'front_vols_list' => [
      'variables' => [
        'vols' => NULL,
        'type' => 'departure'
      ],
      'template' => 'front/vols-list',
    ],


    'admin_status_list' => [
      'variables' => [
        'items' => NULL,
        "total_row" => 0,
        "total_item" => 0,
        "page" => 0,
        "limit" => 15,
        "nbre_page" => 1,
      ],
      'template' => 'admin/status/list',
    ],

    'admin_status_view' => [
      'variables' => [
        'status' => NULL
      ],
      'template' => 'admin/status/view',
    ],


    'admin_airport_list' => [
      'variables' => [
        'items' => NULL,
        "total_row" => 0,
        "total_item" => 0,
        "page" => 0,
        "limit" => 15,
        "nbre_page" => 1,
      ],
      'template' => 'admin/airport/list',
    ],

    'admin_airport_view' => [
      'variables' => [
        'airport' => NULL
      ],
      'template' => 'admin/airport/view',
    ],


    'admin_company_list' => [
      'variables' => [
        'items' => NULL,
        "total_row" => 0,
        "total_item" => 0,
        "page" => 0,
        "limit" => 15,
        "nbre_page" => 1,
      ],
      'template' => 'admin/company/list',
    ],

    'admin_company_view' => [
      'variables' => [
        'company' => NULL
      ],
      'template' => 'admin/company/view',
    ],


    'admin_vol_list' => [
      'variables' => [
        'items' => NULL,
        "total_row" => 0,
        "total_item" => 0,
        "page" => 0,
        "limit" => 15,
        "nbre_page" => 1,
      ],
      'template' => 'admin/vol/list',
    ],

    'admin_vol_view' => [
      'variables' => [
        'vol' => NULL
      ],
      'template' => 'admin/vol/view',
    ],

  ];
}

/**
 * Implements hook_library_info().
 */
function vols_library_info() {
  $libraries = [];

  $libraries['vols/custom'] = [
    'title' => 'Custom CSS and JavaScript',
    'version' => '1.0',
    'css' => [
      'assets/css/vols.css' => [],
    ],
    'js' => [
      'assets/js/vols.js' => [],
    ],
  ];

  return $libraries;
}

/**
 * Implements hook_page_attachments().
 */
function vols_page_attachments(array &$attachments) {
  // Attache le fichier CSS et js personnalisé à chaque page.
  $attachments['#attached']['library'][] = 'vols/custom';
}
